//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using COM;
    
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HasmaEntities : DbContext
    {
        public HasmaEntities()
            : base("name=HasmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bon> Bons { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Ghest> Ghests { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PurchaseZarinpalLog> PurchaseZarinpalLogs { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserBon> UserBons { get; set; }
        public virtual DbSet<UserDocument> UserDocuments { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
    
        public virtual ObjectResult<LoginByActiveCode_Result> LoginByActiveCode(string tellnumber, string activecode)
        {
            var tellnumberParameter = tellnumber != null ?
                new ObjectParameter("tellnumber", tellnumber) :
                new ObjectParameter("tellnumber", typeof(string));
    
            var activecodeParameter = activecode != null ?
                new ObjectParameter("activecode", activecode) :
                new ObjectParameter("activecode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginByActiveCode_Result>("LoginByActiveCode", tellnumberParameter, activecodeParameter);
        }
    }
}
