//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CatID { get; set; }
        public string Name { get; set; }
        public int SubCatID { get; set; }
        public string SubName { get; set; }
        public string Group { get; set; }
        public string ImgName { get; set; }
    }
}
