//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int FID { get; set; }
        public string Name { get; set; }
        public string ImageID { get; set; }
        public bool IsBaner { get; set; }
    }
}
