//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghest
    {
        public int ID { get; set; }
        public double Percentage { get; set; }
        public int MaxGhestNumber { get; set; }
        public int MinGhestNumber { get; set; }
        public long MaxGhestValue { get; set; }
        public long MinGhestValue { get; set; }
        public long MinPishPardakht { get; set; }
    }
}
