//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OID { get; set; }
        public int UID { get; set; }
        public string BuyID { get; set; }
        public System.DateTime OrderTime { get; set; }
        public bool PayStatus { get; set; }
        public bool IsDelivered { get; set; }
        public string ReciverInfo { get; set; }
        public string ProductsInfo { get; set; }
        public int TypePay { get; set; }
        public int GhestNumber { get; set; }
        public long GhestValue { get; set; }
        public long MainPrice { get; set; }
        public long PishPardakht { get; set; }
    }
}
