//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int PayID { get; set; }
        public int UID { get; set; }
        public int OID { get; set; }
        public string BuyID { get; set; }
        public long Amount { get; set; }
        public System.DateTime StartMoment { get; set; }
        public Nullable<int> DargahState { get; set; }
        public string Token { get; set; }
        public string TrackingNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> EndMoment { get; set; }
        public Nullable<bool> IsReverse { get; set; }
        public Nullable<int> FinalState { get; set; }
    }
}
