//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseZarinpalLog
    {
        public int ZPID { get; set; }
        public string Autohority { get; set; }
        public long RefID { get; set; }
        public int Status { get; set; }
        public int UID { get; set; }
        public System.DateTime PayDate { get; set; }
        public int Amount { get; set; }
        public string Product { get; set; }
        public int OID { get; set; }
    }
}
