//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDocument
    {
        public int UID { get; set; }
        public int KartMeli { get; set; }
        public int KasrHoghoogh { get; set; }
        public int JavazKasb { get; set; }
        public int FishHoghoogh { get; set; }
        public int CheckZemanat { get; set; }
        public Nullable<System.DateTime> LastUpTime { get; set; }
        public Nullable<System.DateTime> VerifiedTime { get; set; }
        public bool Verified { get; set; }
    }
}
